// eslint-disable-next-line import/prefer-default-export
export const FETCH_MAINPAGE_START = 'FETCH_MAINPAGE_START';
export const FETCH_MAINPAGE_FAILURE = 'FETCH_MAINPAGE_FAILURE';
export const FETCH_MAINPAGE_SUCCESS = 'FETCH_MAINPAGE_SUCCESS';
export const UPDATE_CART = 'UPDATE_CART';
export const FETCH_CATALOG_START = 'FETCH_CATALOG_START';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_PROMO_START = 'FETCH_PROMO_START';
export const FETCH_PROMO_FAILURE = 'FETCH_PROMO_FAILURE';
export const FETCH_PROMO_SUCCESS = 'FETCH_PROMO_SUCCESS';
export const DELETE_PROMO = 'DELETE_PROMO';
